Add NestJS tools libraries related to file storage and AMQP trasnport
nestjs/awesome-nestjs pull request #297
Opened 2024-07-17 08:22 UTC by getlarge

## Resource type _(required)_

- [x] GitHub Repository:
    - [x] **(Required)** I confirm that the GitHub repository has more than **10 stars**.
    - [x] **(Required)** The repository is not archived.
- [ ] Video.
- [ ] Tutorial.
- [ ] Meetups.
- [ ] Improve documentation _(grammatical corrections, improve doc style, ...)_.

> If your contribution is NOT a GitHub repository, then you can skip the next titles, except "Rules".

## Description _(required)_

The `NestJS tools` contain libraries written over the past 4 years to provide reusable solutions for applications running in production.
I included three of those libraries, which I think are the most helpful and seemed to be missing during my research for equivalent.

## Link _(required)_

https://github.com/getlarge/nestjs-tools

## Rules _(required)_

- [x] **NestJS / Nest**: It's not nest, nestjs, nest.js, and other variants.
- [x] **Node.js**: It's not nodejs, node, and other variants.

2024-07-25 22:52 UTC, micalevisk commented on README.md
> +- ![](https://img.shields.io/github/stars/getlarge/nestjs-tools.svg?style=flat-square) [@getlarge/nestjs-tools-fastify-upload](https://github.com/getlarge/nestjs-tools/tree/main/packages/fastify-uplo
```suggestion
- ![](https://img.shields.io/github/stars/getlarge/nestjs-tools.svg?style=flat-square) [`@getlarge/nestjs-tools-file-storages`](https://github.com/getlarge/nestjs-tools/blob/main/packages/file-storage) - A FileStorage Module supporting several strategies (**FS**, **S3**, **GCP storage**) to store files.
- ![](https://img.shields.io/github/stars/getlarge/nestjs-tools.svg?style=flat-square) [`@getlarge/nestjs-tools-fastify-upload`](https://github.com/getlarge/nestjs-tools/tree/main/packages/fastify-upload) - Suite of Interceptors and request decorators to handle file upload with **Fastify**.
```

2024-07-25 22:53 UTC, micalevisk requested changes
fix formatting

2024-07-25 22:53 UTC, micalevisk commented on README.md
> +- ![](https://img.shields.io/github/stars/getlarge/nestjs-tools.svg?style=flat-square) [@getlarge/nestjs-tools-amqp-transport](https://github.com/getlarge/nestjs-tools/tree/main/packages/amqp-transpo
```suggestion
- ![](https://img.shields.io/github/stars/getlarge/nestjs-tools.svg?style=flat-square) [`@getlarge/nestjs-tools-amqp-transport`](https://github.com/getlarge/nestjs-tools/tree/main/packages/amqp-transport) - An extended **AMQP** transport strategy supporting **exchanges**.
```

2024-07-26 04:40 UTC, getlarge commented on README.md
> +- ![](https://img.shields.io/github/stars/getlarge/nestjs-tools.svg?style=flat-square) [@getlarge/nestjs-tools-amqp-transport](https://github.com/getlarge/nestjs-tools/tree/main/packages/amqp-transpo
My eyes are bad that day :). Fixed.

2024-07-26 18:51 UTC, jmcdo29 approved these changes

2024-07-26 18:51 UTC, merged