Update README.md
nestjs/awesome-nestjs pull request #299
Opened 2024-08-15 21:25 UTC by MoeidHeidari

new nests boilerplate

## Resource type _(required)_

- [ ] GitHub Repository:
    - [ ] **(Required)** I confirm that the GitHub repository has more than **10 stars**.
    - [ ] **(Required)** The repository is not archived.
- [ ] Video.
- [ ] Tutorial.
- [ ] Meetups.
- [ ] Improve documentation _(grammatical corrections, improve doc style, ...)_.

> If your contribution is NOT a GitHub repository, then you can skip the next titles, except "Rules".

## Description _(required)_

_Brief description of the resource you are adding._

## Link _(required)_

_Paste link here._

## Rules _(required)_

- [ ] **NestJS / Nest**: It's not nest, nestjs, nest.js, and other variants.
- [ ] **Node.js**: It's not nodejs, node, and other variants.

2024-08-16 11:23 UTC, micalevisk commented on README.md
> +- [Clean NestJs architecture]([https://github.com/MoeidHeidari/Location-based-searcher](https://github.com/MoeidHeidari/sudoku-challenge)) - This boilerplate show how to setup a clean architecture wi
the hyperlink is malformed here

2024-08-17 14:21 UTC, micalevisk requested changes
Fix the hyperlink

2024-08-17 19:42 UTC, MoeidHeidari commented on README.md
> +- [Clean NestJs architecture]([https://github.com/MoeidHeidari/Location-based-searcher](https://github.com/MoeidHeidari/sudoku-challenge)) - This boilerplate show how to setup a clean architecture wi
Fixed

2024-08-17 22:03 UTC, micalevisk approved these changes

2024-08-19 15:45 UTC, jmcdo29 approved these changes

2024-08-19 15:45 UTC, merged