feat: add new references for nestjs-firebase-auth in README
nestjs/awesome-nestjs pull request #301
Opened 2024-09-05 17:41 UTC by Alpha018

## Resource type

- [x] GitHub Repository:
    - [x] **(Required)** I confirm that the GitHub repository has more than **10 stars**.
    - [x] **(Required)** The repository is not archived.
- [ ] Video.
- [x] Tutorial.
- [ ] Meetups.
- [x] Improve documentation _(grammatical corrections, improve doc style, ...)_.

## Description

This library streamlines the integration of Firebase authentication into your NestJS application. It provides a convenient way to verify Firebase user tokens and includes an optional user role management system, making it easier to control access levels within your app. Additionally, the library exposes the Firebase instance itself, allowing for flexible use of Firebase services such as Firestore, Storage, and more. Whether you're building a small project or scaling up, this tool will help you manage authentication and authorization in a seamless and efficient way.

## Link

https://github.com/Alpha018/nestjs-firebase-auth

## Rules

- [x] **NestJS / Nest**: It's not nest, nestjs, nest.js, and other variants.
- [x] **Node.js**: It's not nodejs, node, and other variants.

2024-09-07 15:28 UTC, micalevisk approved these changes

2024-09-10 16:46 UTC, jmcdo29 requested changes
We probably should only have one mention of the library in the README. Whichever you feel is more appropriate for the module

2024-09-10 16:53 UTC, jmcdo29 approved these changes

2024-09-10 16:53 UTC, merged

2024-09-10 16:53 UTC, Alpha018 commented
I understand the change, I'll leave it in that case in the Auth part since it provides a couple of functions to handle user roles, but it works for both cases in general; I tried to improve the description a bit more anyway